refactoring code

diff --git a/block_1/matrix b/block_1/matrix
--- a/block_1/matrix
+++ b/block_1/matrix
@@ -95,22 +95,19 @@ function check_matrix_dimensions() {
         numOfItems2="$(wc -w < $3)"
         numOfCols2="$(( numOfItems2 / numOfRows2 ))"
 
-
-	if [[ $1 == "add" ]] 
+	# If add operation, but matrices are the same dimensions, print error
+	# message and return 1,	
+	if [[ "${1}" == "add" && "${numOfRows1} -ne "${numOfRows2}" ||
+		 "${1}" == "add" && "${numOfCols1} -ne "${numOfCols2}" ]] 
 	then 
-		if [[ $numOfRows1 -ne $numOfRows2 ]] || [[ $numOfCols1 -ne $numOfCols2 ]]
-		then			
-			>&2 echo "Error: You cannot use the add function on matrices of different sizes."
-			exit 1
-		fi	
-	elif [[ $1 == "multiply" ]]
+		>&2 echo "Error: You cannot add matrices of different sizes."
+		exit 1
+	# If multiply operation, but matrix 1's number of colums does not 
+	# equal matrix 2's number of rows, print error and return 1.
+	elif [[ "${1}" == "multiply" && "${numOfCols1}" -ne "${numOfRows2}" ]]
 	then
-	# The number of columns in the first matrix must be equal to the number of rows in the second matrix.
-		if [[ $numOfCols1 -ne $numOfRows2 ]]
-		then 
-			>&2 echo "Error: You cannot multiply these matrices."
-			exit 1
-		fi
+		>&2 echo "Error: You cannot multiply these matrices."
+		exit 1
 	fi	
 }
 
