tiny fix to matrix unknown operation catch

diff --git a/block_1/matrix b/block_1/matrix
--- a/block_1/matrix
+++ b/block_1/matrix
@@ -369,7 +369,8 @@ function main() {
 			multiplyMatrices $2 $3
 			;;
 		*)
-			echo "OPERATION UNKNOWN!!!"
+			>&2 echo "ERROR: Operation '$1' unknown."
+                        exit 1	
 			;;
 	esac
 }
